import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Anastasiia',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'iPhone 14 Pro Max',
      slug: 'iphone-14-pro-max',
      category: 'Phone',
      image: '/images/iphone14promax.jpg',
      price: 1400,
      brand: 'Apple',
      rating: 5,
      countInStock: 200,
      description: "iPhone 14 Pro Max mobile was launched on 7th September 2022. The phone comes with a 120 Hz refresh rate 6.70-inch touchscreen display offering a resolution of 2796x1290 pixels at a pixel density of 460 pixels per inch (ppi). The display sports Other for protection. iPhone 14 Pro Max is powered by a hexa-core Apple A16 Bionic processor. The iPhone 14 Pro Max supports wireless charging, as well as proprietary fast charging. As far as the cameras are concerned, the iPhone 14 Pro Max on the rear packs a triple camera setup featuring a 48-megapixel (f/1.78) primary camera; a 12-megapixel (f/2.2) camera, and a 12-megapixel (f/1.78) camera. It has a single front camera setup for selfies, featuring a 12-megapixel sensor with an f/1.9 aperture. iPhone 14 Pro Max is based on iOS 16 and packs 128GB, 256GB, 512GB, 1TB of inbuilt storage. The iPhone 14 Pro Max measures 160.70 x 77.60 x 7.85mm (height x width x thickness) and weighs 240.00 grams. It was launched in Space Black, Silver, Gold, and Deep Purple colours. It features an IP68 rating for dust and water protection. Connectivity options on the iPhone 14 Pro Max include Wi-Fi and Lightning. Sensors on the phone include accelerometer, ambient light sensor, proximity sensor, and compass/ magnetometer.",
    },
    {
      name: 'iPhone 14 Pro',
      slug: 'iphone-14-pro',
      category: 'Phone',
      image: '/images/iphone14pro.jpg',
      price: 1300,
      brand: 'Apple',
      rating: 5,
      countInStock: 110,
      description: "The iPhone 14 Pro introduces a new Dynamic Island area instead of a notch, an upgraded 48-megapixel primary camera, and an always-on display. Other improvements such as crash detection and emergency satellite-based SMS communication aren't entirely relevant in India at the time of launch. It's available with 128GB, 256GB, 512GB or 1TB of storage. The new Deep Purple colour option is quite striking but not much has changed about this phone's looks compared to its past two predecessors. You get the A16 Bionic SoC on the inside, which powers only the new iPhone 14 Pro and 14 Pro Max this year. Battery life is decent, and everyday performance is very slick. iOS 16 has a few improvements to customisation and personalisation as well. All three rear cameras as well as the one in front have been improved in terms of low-light capabilities, and there's an Action Mode for video that delivers cropped and stabilised frames.",
    },
    {
      name: 'iPhone 13',
      slug: 'iphone-13',
      category: 'Phone',
      image: '/images/iphone13.jpg',
      price: 1050,
      brand: 'Apple',
      rating: 4,
      countInStock: 60,
      description: "The iPhone 13 brings a few subtle updates compared to the iPhone 12, but you might find that the previous year's model offers better value. This phone has a bright, vibrant 6.1-inch OLED screen, but with only a 60Hz refresh rate and an annoying notch. The A15 Bionic SoC provides more than enough power for gaming and heavy apps. The cameras are versatile and deliver great quality for stills as well as video, plus you get the same Cinematic Mode and Photographic Styles features as on the more expensive iPhone 13 Pro. Battery life is good, but not great. iOS 15 keeps everything running smoothly. You can choose between 128GB, 256GB and 512GB of storage. The iPhone 13 mini is equivalent in terms of features and performance",
    },
    {
      name: 'iPhone 13 Pro',
      slug: 'iphone-13-pro',
      category: 'Phone',
      image: '/images/iphone13pro.jpg',
      price: 1150,
      brand: 'Apple',
      rating: 4,
      countInStock: 66,
      description: "The iPhone 13 Pro has all the same hardware as the iPhone 13 Pro Max except for a smaller battery and display. You get sensor-shift stabilisation for the primary camera, and for the first time, you can take macro photos. Optical zoom also goes up to 3X. Apple has introduced new camera features, Cinematic Mode and Photographic Styles. Beyond that, the new A15 Bionic SoC delivers excellent performance. Storage goes up to 1TB, though the top-end variant is extremely expensive. The 120Hz ProMotion display is a big improvement but there's still an awkward notch that can be distracting. Games and apps run very well, and the stereo speakers are also quite good. Construction quality is excellent and the iPhone 13 Pro is easier to hold and use than its bigger sibling.",
    },
    {
      name: 'iPhone 12 Pro',
      slug: 'iphone-12pro',
      category: 'Phone',
      image: '/images/iphone12pro.jpg',
      price: 1000,
      brand: 'Apple',
      rating: 5,
      countInStock: 90,
      description: "iPhone 12 Pro mobile was launched on 13th October 2020. The phone comes with a 6.10-inch touchscreen display offering a resolution of 1170x2532 pixels at a pixel density of 460 pixels per inch (ppi). The display sports Other for protection. iPhone 12 Pro is powered by a hexa-core Apple A14 Bionic processor. The iPhone 12 Pro supports wireless charging, as well as proprietary fast charging As far as the cameras are concerned, the iPhone 12 Pro on the rear packs a 12-megapixel (f/1.6) primary camera; a 12-megapixel (f/2.4) camera, and a 12-megapixel (f/2.0) camera. The rear camera setup has autofocus. It sports a 12-megapixel camera on the front for selfies with an f/2.2 aperture. iPhone 12 Pro is based on iOS 14 and packs 64GB of inbuilt storage. The iPhone 12 Pro is a dual-SIM (GSM and GSM) mobile that accepts Nano-SIM and eSIM cards. The iPhone 12 Pro measures 146.70 x 71.50 x 7.40mm (height x width x thickness) and weighs 189.00 grams. It was launched in Gold, Graphite, Pacific Blue, and Silver colours. It features an IP68 rating for dust and water protection. Connectivity options on the iPhone 12 Pro include Wi-Fi 802.11 a/b/g/n/ac/ax, GPS, Bluetooth v5.00, NFC, Lightning, 3G, 4G (with support for Band 40 used by some LTE networks in India) , and 5G. Sensors on the phone include accelerometer, ambient light sensor, barometer, gyroscope, proximity sensor, and compass/ magnetometer. The iPhone 12 Pro supports face unlock with 3D face recognition.",
    },
    {
      name: 'iPhone 12',
      slug: 'iphone-12',
      category: 'Phone',
      image: '/images/iphone12.jpg',
      price: 900,
      brand: 'Apple',
      rating: 5,
      countInStock: 69,
      description: "The iPhone 12 costs more than its predecessors but has a crisp new HDR OLED screen. It offers nearly all the feaures of the iPhone 12 Pro, minus some camera capabilities, but should be a good enough package for most users. Apple has returned to a flat aluminium frame but the iPhone 12 promises to be more durable thanks to its Ceramic Shield material on the front and IP68 rating You get the A14 Bionic SoC which makes everyday use extremely smooth and responsive, but the device does get a bit warm when stressed. Battery life is good, but not great, and you'll be able to get through a full day. The iPhone 12 is relatively light and easy to handle. iOS 14 has some new customisation options and privacy features. You get two rear cameras - a wide-angle and an ultra-wide-angle one, which both have 12-megapixel sensors. Night mode now works across all cameras including the front one, and still shots as well as videos are remarkably sharp and detailed in the daytime as well as at night.",
    },
    {
      name: 'iPhone XS',
      slug: 'iphone-xs',
      category: 'Phone',
      image: '/images/iphonexs.jpg',
      price: 850,
      brand: 'Apple',
      rating: 5,
      countInStock: 100,
      description: "Apple iPhone XS mobile was launched in September 2018. The phone comes with a 5.80-inch touchscreen display offering a resolution of 1125x2436 pixels at a pixel density of 458 pixels per inch (ppi). The display sports Other for protection. Apple iPhone XS is powered by a hexa-core Apple A12 Bionic processor. The Apple iPhone XS supports wireless charging, as well as proprietary fast charging. As far as the cameras are concerned, the Apple iPhone XS on the rear packs a 12-megapixel (f/1.8, 1.4-micron) primary camera, and a 12-megapixel (f/2.4) camera. The rear camera setup has autofocus. It sports a 7-megapixel camera on the front for selfies with an f/2.2 aperture. Apple iPhone XS is based on iOS 12 and packs 64GB of inbuilt storage. The Apple iPhone XS is a dual-SIM (GSM and GSM) mobile that accepts Nano-SIM and eSIM cards. The Apple iPhone XS measures 143.60 x 70.90 x 7.70mm (height x width x thickness) and weighs 177.00 grams. It was launched in Gold, Silver, and Space Grey colours. It features an IP68 rating for dust and water protection. Connectivity options on the Apple iPhone XS include Wi-Fi 802.11 a/b/g/n/ac, GPS, Bluetooth v5.00, NFC, Lightning, 3G, and 4G (with support for Band 40 used by some LTE networks in India) with active 4G on both SIM cards. Sensors on the phone include accelerometer, ambient light sensor, barometer, gyroscope, proximity sensor, and compass/ magnetometer. The Apple iPhone XS supports face unlock with 3D face recognition.",
    },
    {
      name: 'iPhone XR',
      slug: 'iphone-xr',
      category: 'Phone',
      image: '/images/iphonexr.jpg',
      price: 750,
      brand: 'Apple',
      rating: 5,
      countInStock: 90,
      description: "Apple iPhone XR mobile was launched in September 2018. The phone comes with a 6.10-inch touchscreen display offering a resolution of 828x1792 pixels at a pixel density of 326 pixels per inch (ppi) and an aspect ratio of 19.5:9. The display sports Other for protection. Apple iPhone XR is powered by a hexa-core Apple A12 Bionic processor. It comes with 3GB of RAM. The Apple iPhone XR runs iOS 12 and is powered by a 2942mAh non-removable battery. The Apple iPhone XR supports wireless charging, as well as proprietary fast charging. As far as the cameras are concerned, the Apple iPhone XR on the rear packs a 12-megapixel camera with an f/1.8 aperture. The rear camera setup has autofocus. It sports a 7-megapixel camera on the front for selfies with an f/2.2 aperture. Apple iPhone XR is based on iOS 12 and packs 64GB of inbuilt storage. The Apple iPhone XR is a dual-SIM (GSM and GSM) mobile that accepts Nano-SIM and eSIM cards. The Apple iPhone XR measures 150.90 x 75.70 x 8.30mm (height x width x thickness) and weighs 194.00 grams. It was launched in 0, Black, Blue, Coral, Red, White, and Yellow colours. It features an IP67 rating for dust and water protection. Connectivity options on the Apple iPhone XR include Wi-Fi 802.11 a/b/g/n/ac, GPS, Bluetooth v5.00, NFC, Lightning, 3G, and 4G (with support for Band 40 used by some LTE networks in India) with active 4G on both SIM cards. Sensors on the phone include accelerometer, ambient light sensor, barometer, gyroscope, proximity sensor, and compass/ magnetometer. The Apple iPhone XR supports face unlock with 3D face recognition.",
    },
    {
      name: 'iPhone X',
      slug: 'iphone-x',
      category: 'Phone',
      image: '/images/iphonex.jpg',
      price: 800,
      brand: 'Apple',
      rating: 3,
      countInStock: 80,
      description: "The iPhone X has to be one of the most-talked about tech products of 2017, and introduces a brand new paradigm for interaction, with gestures replacing buttons and a larger screen than on any previous iPhone. It shares most of its internals with the iPhone 8 and iPhone 8 Plus, including Apple’s own A11 Bionic chip and support for wireless charging. However, the 5.8-inch AMOLED panel is a first for any iPhone. Overall, the iPhone X display is great. The notch at the top contains the front camera and 3D sensors that make Face ID recognition possible. It works seamlessly and reliably on most occasions. Attention detection ensures that no one can unlock your iPhone X by simply pointing the device at your face when you are not looking. Animoji is a cool new feature that lets you pick an emoji and animate it using your own facial movements. You get optical image stabilisation on both rear cameras, and the iPhone X takes great pictures in nearly all scenarios.",
    },
    {
      name: 'iPhone 8 Plus',
      slug: 'iphone-8plus',
      category: 'Phone',
      image: '/images/iphone8plus.jpg',
      price: 750,
      brand: 'Apple',
      rating: 5,
      countInStock: 100,
      description: "The iPhone 8 Plus is a larger version of the iPhone 8, with a larger screen and battery, more RAM, and a secondary telephoto camera on the rear. It's powered by the same A11 Bionic processor as the iPhone X, which has been shown to be exceptionally powerful, especially in tests that can utilise all six cores at the same time. The display now supports True Tone which adjusts its colour temperature to match ambient lighting. You get 64GB of storage on the base variant but can choose a 256GB option which costs more. Your only choices of colours this time around are Space Grey, Silver, and Gold. The iPhone 8 models also feature new glass backs to support wireless charging, while maintaining the IP67 rating for water and dust resistance. Fast wired charging is supported but you only get a basic charger in the box. You can get through a full day of use with a little power to spare thanks to the large battery.",
    },
    {
      name: 'iPhone 8',
      slug: 'iphone-8',
      category: 'Phone',
      image: '/images/iphone8.jpg',
      price: 700,
      brand: 'Apple',
      rating: 3,
      countInStock: 90,
      description: "The iPhone 8 has been launched alongside the more expensive iPhone X. It looks much like its predecessor, the iPhone 7, but introduces a new glass back to allow for wireless charging. It's available in Space Grey, Silver, and Gold, with 64GB and 256GB storage options at launch time. You get Apple's powerful A11 Bionic processor with six cores, which has beaten the current-generation processors used in flagship Android smartphones. The display now supports True Tone colour temperature adjustment to match ambient lighting. The IP67 rating promises water and dust resistance to some extent. There's a single 12-megapixel rear camera and you can record video at up to 4K 60fps or 1080p 240fps. If you want a telephoto camera as well you'll have to step up to the iPhone 8 Plus. Battey life is just about enough to get you through one working day.",
    },
    {
      name: 'iPhone 7 Plus',
      slug: 'iphone-7plus',
      category: 'Phone',
      image: '/images/iphone7plus.jpg',
      price: 600,
      brand: 'Apple',
      rating: 5,
      countInStock: 60,
      description: "The iPhone 7 and iPhone 7 Plus launch this September represented a departure from tradition for Apple - and in many ways, a risk. Instead of the usual tick-tock cycle where each ’S’ release is followed by a brand-new design, the new iPhone models look pretty similar to their counterparts from the previous two years, and sport nearly identical dimensions. There are more changes than there are in a typical ‘S’ cycle, but if you have a Rose Gold iPhone 6s or a Silver iPhone 6 Plus, for example, the differences may not be apparent at first glance. In a world in which a device’s reception is driven by its looks, it was no surprise that the initial reaction to iPhone 7 and iPhone 7 Plus was lukewarm. Apple didn’t help matters with the 'courageous' move of dropping the headphone port, with everyone and their friend Jack outraged even before anyone had a chance to test the impact of the move in the real world. So how do the new iPhone models stack up against their predecessors and competing flagships from the Android world? Like last year, we’ve spent more time than we do with most phones before sharing our thoughts with you, and here’s our review of the iPhone 7 and iPhone 7 Plus.",
    },
    {
      name: 'iPhone 7',
      slug: 'iphone-7',
      category: 'Phone',
      image: '/images/iphone7.jpg',
      price: 550,
      brand: 'Apple',
      rating: 4,
      countInStock: 70,
      description: "Apple iPhone 7 mobile was launched in September 2016. The phone comes with a 4.70-inch touchscreen display offering a resolution of 750x1334 pixels at a pixel density of 326 pixels per inch (ppi) and an aspect ratio of 16:9. Apple iPhone 7 is powered by a 2.34GHz quad-core Apple A10 Fusion processor. It comes with 2GB of RAM. The Apple iPhone 7 runs iOS 10 and is powered by a 1960mAh non-removable battery. As far as the cameras are concerned, the Apple iPhone 7 on the rear packs a 12-megapixel camera with an f/1.8 aperture. The rear camera setup has phase detection autofocus. It sports a 7-megapixel camera on the front for selfies with an f/2.2 aperture. Apple iPhone 7 is based on iOS 10 and packs 32GB of inbuilt storage. The Apple iPhone 7 is a single SIM (GSM) mobile that accepts a Nano-SIM card. The Apple iPhone 7 measures 138.30 x 67.10 x 7.10mm (height x width x thickness) and weighs 138.00 grams. It was launched in Black, Gold, Jet Black, Matte Black, Red, Rose Gold, and Silver colours. Connectivity options on the Apple iPhone 7 include Wi-Fi 802.11 a/b/g/n/ac, GPS, Bluetooth v4.20, NFC, Lightning, 3G, and 4G (with support for Band 40 used by some LTE networks in India). Sensors on the phone include accelerometer, ambient light sensor, barometer, compass/ magnetometer, gyroscope, proximity sensor, and fingerprint sensor.",
    },
    {
      name: 'iPhone 6s',
      slug: 'iphone-6s',
      category: 'Phone',
      image: '/images/iphone6s.jpg',
      price: 500,
      brand: 'Apple',
      rating: 4,
      countInStock: 60,
      description: "Apple iPhone 6s mobile was launched in September 2015. The phone comes with a 4.70-inch touchscreen display offering a resolution of 750x1334 pixels at a pixel density of 326 pixels per inch (ppi) and an aspect ratio of 16:9. Apple iPhone 6s is powered by a 1.84GHz dual-core Apple A9 processor. It comes with 2GB of RAM. The Apple iPhone 6s runs iOS 9 and is powered by a 1715mAh non-removable battery. As far as the cameras are concerned, the Apple iPhone 6s on the rear packs a 12-megapixel camera with an f/2.2 aperture and a pixel size of 1.22-micron. The rear camera setup has phase detection autofocus. It sports a 5-megapixel camera on the front for selfies with an f/2.2 aperture. Apple iPhone 6s is based on iOS 9 and packs 16GB of inbuilt storage. The Apple iPhone 6s is a single SIM (GSM) mobile that accepts a Nano-SIM card. The Apple iPhone 6s measures 138.30 x 67.10 x 7.10mm (height x width x thickness) and weighs 143.00 grams. It was launched in Gold, Rose Gold, Silver, and Space Grey colours. It bears a metal body. Connectivity options on the Apple iPhone 6s include Wi-Fi 802.11 a/b/g/n/ac, GPS, Bluetooth v4.20, NFC, Lightning, 3G, and 4G (with support for Band 40 used by some LTE networks in India). Sensors on the phone include accelerometer, ambient light sensor, barometer, compass/ magnetometer, gyroscope, proximity sensor, and fingerprint sensor.",
    },
    {
      name: 'iPhone 5s',
      slug: 'iphone-5s',
      category: 'Phone',
      image: '/images/iphone5s.jpg',
      price: 400,
      brand: 'Apple',
      rating: 4,
      countInStock: 20,
      description: "The iPhone 5s is not a radical departure in design for Apple, save for one very important feature. No, we don't mean the new Space Gray and Gold colors. We have in mind the home button that has been on iPhones from day one, is now turned into a fingerprint scanner dubbed Touch ID. It lets you unlock the phone and authorize purchases, safely storing your fingerprints in the A7 processor itself, out of the reach for anyone but a few default iOS 7 apps. This A7 processor debuts on the iPhone 5s as the first 64-bit mobile chipset in use on a commercial device, utilized by the latest flat and minimalistic iOS 7 that has been rewritten to take advantage of the 64-bit system. It sports a dedicated M7 co-processor for always-on motion sensing, too. The iSight camera stayed 8 MP, but is much improved, with larger pixels, wider aperture, and the ability to shoot slow motion videos, not to mention the dual two-tone LED flash on the back that strives for natural skin color representation.",
    },
    {
      name: "MacBook Pro 'M1 Pro' 14''",
      slug: 'macbook-pro-14-2021',
      category: 'Notebook',
      image: '/images/macbook-pro-14-2021.jpg',
      price: 1400,
      brand: 'Apple',
      rating: 4,
      countInStock: 20,
      description: "The Apple MacBook Pro 'M1 Pro' 8-Core CPU/14-Core GPU 14-Inch (2021) model features a 3.2 GHz Apple M1 Pro processor with eight cores (6 performance cores and 2 efficiency cores), a 14-core GPU, a 16-core Neural Engine, 16 GB of onboard RAM, and a 512 GB onboard SSD. Both the RAM and the SSD could be upgraded at the time of initial system purchase, but not subsequently. Offered in silver and a darker 'Space Gray' color, this notebook has an integrated 1080p FaceTime HD webcam, a 'high-fidelity six-speaker sound system with force-cancelling woofers,' a backlit 'Magic Keyboard' with a 'Touch ID' sensor (but no 'Touch Bar'), and a gigantic 'Force Touch' trackpad. Additionally, it has a high-resolution LED-backlit 14.2' widescreen 3024x1964 (254 ppi, 1000 nits sustained, 1600 nits peak, 1,000,000:1 contrast ratio) 'Liquid Retina XDR' display, and a integrated battery that provides an Apple estimated 11-17 hours of runtime. Connectivity includes 802.11ax Wi-Fi 6, Bluetooth 5, three Thunderbolt 4 ports (USB-C connector), an HDMI 2.0 port, an SDXC-capable SD card slot, a 3.5 mm headphone jack, and a 'MagSafe 3' power connector. Compared to its predecessor, the 14' '2021' MacBook Pro has little in common. The '2021' MacBook Pro models have a better quality display, simpler keyboard, much more significant external connectivity, and a completely different internal architecture that boasts faster performance.",
    },
    {
      name: "MacBook Pro 'M1 Pro' 16''",
      slug: 'macbook-pro-16-2021',
      category: 'Notebook',
      image: '/images/macbook-pro-16-2021.jpg',
      price: 1600,
      brand: 'Apple',
      rating: 5,
      countInStock: 18,
      description: "The Apple MacBook Pro 'M1 Pro' 8-Core CPU/14-Core GPU 16-Inch (2021) model features a 3.2 GHz Apple M1 Pro processor with eight cores (6 performance cores and 2 efficiency cores), a 14-core GPU, a 16-core Neural Engine, 16 GB of onboard RAM, and a 512 GB onboard SSD. Both the RAM and the SSD could be upgraded at the time of initial system purchase, but not subsequently. Offered in silver and a darker 'Space Gray' color, this notebook has an integrated 1080p FaceTime HD webcam, a 'high-fidelity six-speaker sound system with force-cancelling woofers,' a backlit 'Magic Keyboard' with a 'Touch ID' sensor (but no 'Touch Bar'), and a gigantic 'Force Touch' trackpad. Additionally, it has a high-resolution LED-backlit 14.2' widescreen 3024x1964 (254 ppi, 1000 nits sustained, 1600 nits peak, 1,000,000:1 contrast ratio) 'Liquid Retina XDR' display, and a integrated battery that provides an Apple estimated 11-17 hours of runtime. Connectivity includes 802.11ax Wi-Fi 6, Bluetooth 5, three Thunderbolt 4 ports (USB-C connector), an HDMI 2.0 port, an SDXC-capable SD card slot, a 3.5 mm headphone jack, and a 'MagSafe 3' power connector. Compared to its predecessor, the 16' '2021' MacBook Pro has little in common. The '2021' MacBook Pro models have a better quality display, simpler keyboard, much more significant external connectivity, and a completely different internal architecture that boasts faster performance.",
    },
    {
      name: "Apple Watch Series 7",
      slug: 'watch-series-7',
      category: 'Accessories',
      image: '/images/watch-series-7.jpg',
      price: 600,
      brand: 'Apple',
      rating: 5,
      countInStock: 85,
      description: "The Apple Watch 7 replaced the Watch 6 as the premium model in Apple's wearable range for 2021, joining the Watch SE and Watch 3 for those wanting a second screen to complement their iPhone. It's wasn't that much of an upgrade over the previous model when we first encountered it – the main difference being the screen; which is 20% larger. It still packs an impressive feature set that makes it worthy of your consideration, or at least did until the Apple Watch 8 arrived on the scene. Even so, it's still finds a place in our best Apple Watch feature, although it has now fallen off our pick of the best smartwatch options outright. Even so, if your heart remains set on the Series 7, you're getting an ideal companion if you hate having to pull your iPhone out of your pocket to check your notifications, as well a decent fitness tracker. You're also getting good heart rate monitoring and a range of useful apps, all wrapped up in an attractive package.",
    },
    {
      name: "Apple Watch Ultra",
      slug: 'watch-ultra',
      category: 'Accessories',
      image: '/images/watch-ultra.jpg',
      price: 700,
      brand: 'Apple',
      rating: 4,
      countInStock: 78,
      description: "Apple in September 2022 introduced the Apple Watch Ultra, a high-end version of the Apple Watch that's been in development for years now. Designed to compete with more expensive fitness-focused smart watches from companies like Garmin, the Apple Watch Ultra is aimed at sports enthusiasts and athletes that need more battery life and more sport-specific performance from of their devices. Apple says the Apple Watch Ultra was built for endurance, exploration, and adventure, and it is the largest Apple Watch to date at 49mm, which is 4mm larger than the 45mm Apple Watch Series 8 that it's being sold alongside. The Apple Watch Ultra features the first redesign we've seen in years with a lightweight aerospace-grade titanium body, flat sapphire crystal face, a larger diameter and deeper grooved Digital Crown, a housing for the side button and an extra physical button on the left side called the Action button.",
    },
    {
      name: "Apple Magic Mouse",
      slug: 'watch-mouse',
      category: 'Accessories',
      image: '/images/magic-mouse.jpg',
      price: 99,
      brand: 'Apple',
      rating: 3,
      countInStock: 48,
      description: "Magic Mouse is wireless and rechargeable, with an optimized foot design that lets it glide smoothly across your desk. The Multi-Touch surface allows you to perform simple gestures such as swiping between web pages and scrolling through documents. The rechargeable battery will power your Magic Mouse for about a month or more between charges. It’s ready to go right out of the box and pairs automatically with your Mac, and it includes a woven USB-C to Lightning Cable that lets you pair and charge by connecting to a USB-C port on your Mac.",
    },
    {
      name: "Apple Air Pods Pro 2",
      slug: 'air-pods-pro-2',
      category: 'Accessories',
      image: '/images/air-pods-pro-2.jpg',
      price: 220,
      brand: 'Apple',
      rating: 5,
      countInStock: 8,
      description: "Rebuilt from the sound up. AirPods Pro (2nd generation) have been reengineered to deliver up to 2x more Active Noise Cancellation. Adaptive Transparency reduces external noise, while Personalized Spatial Audio immerses you in sound. A single charge delivers up to 6 hours of battery life. And Touch control lets you easily adjust volume with a swipe. The revamped MagSafe Charging Case is a marvel on its own with Precision Finding, built-in speaker, and lanyard loop. ",
    },
  ],
};
export default data;
